services:
  - type: web
    name: codsure-backend
    runtime: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    root: codsure-backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: codsure-db
          property: connectionString

databases:
  - name: codsure-db
    databaseName: codsure
    user: codsure_user
    region: singapore
    plan: free 
